In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
import numpy as np
import pandas as pd
import pyLDAvis
import pyLDAvis.sklearn
pyLDAvis.enable_notebook()

In [12]:
data = pd.read_csv('lda_data.csv')

In [18]:
vector = TfidfVectorizer()
X = vector.fit_transform(data['Abstract'])
X.shape

(10707, 24314)

In [19]:
lda_model = LatentDirichletAllocation(n_components=6, learning_method='batch', random_state=0, max_iter=20, n_jobs=-1)
lda_top = lda_model.fit_transform(X)
print(lda_model.components_)
print(lda_model.components_.shape) 

[[0.32851149 3.61782141 0.3122733  ... 0.16714171 0.27951247 0.39515101]
 [0.1666927  0.16717557 0.16669241 ... 0.16666994 0.16669967 0.16669087]
 [0.16669429 0.16672372 0.16669398 ... 0.23112542 0.16670169 0.17016151]
 [0.16667738 0.16698075 0.16667658 ... 0.16666795 0.16667927 0.16667634]
 [0.16669445 0.16709401 0.16669414 ... 0.16667016 0.16670189 0.1666925 ]
 [0.16669364 0.1669213  0.16669333 ... 0.16667021 0.16670086 0.16669174]]
(6, 24314)


In [20]:
# 단어 집합. 1,000개의 단어가 저장됨.
terms = vector.get_feature_names_out()

def get_topics(components, feature_names, n=20):
    for idx, topic in enumerate(components):
        print("Topic %d:" % (idx+1), [feature_names[i] for i in topic.argsort()[:-n - 1:-1]])

get_topics(lda_model.components_, terms)

Topic 1: ['model', 'data', 'learn', 'train', 'privacy', 'federate', 'propose', 'clients', 'network', 'local', 'use', 'attack', 'devices', 'communication', 'approach', 'edge', 'performance', 'framework', 'accuracy', 'global']
Topic 2: ['mus', 'lung', 'cancer', 'survival', 'asd', 'diabetes', 'icps', 'breast', 'fedsl', 'dsl', 'bpfl', 'qml', 'flex', 'pruw', 'oncology', 'liver', 'aqi', 'arrhythmia', 'msp', 'cb']
Topic 3: ['evcs', 'satcoms', 'tse', 'descriptors', 'fedgr', 'blur', 'fda', 'pfa', 'bl', 'slimfl', 'pelta', 'invasion', 'satcom', 'flids', 'nsps', 'emg', 'svs', 'tsr', 'cave', 'fedkit']
Topic 4: ['wireless', 'channel', 'problem', 'energy', 'allocation', 'algorithm', 'optimization', 'convergence', 'communication', 'power', 'resource', 'schedule', 'air', 'scheme', 'edge', 'cache', 'transmission', 'latency', 'propose', 'network']
Topic 5: ['asr', 'fedmp', 'dmfl', 'psp', 'cmp', 'maas', 'adl', 'breathe', 'hdfl', 'fft', 'fedcls', 'cbfl', 'fedpec', 'feddc', 'poe', 'qp', 'rpl', 'fedclar', 'f